### ISSUE TITLE
EXTERMINATE!

### ISSUE THREAD

**Issue by RedMakuta** [nerdcubed-community/n3bot-issues#3]
**Your Discord Name:** RedRoverCat#0400

**This is a: (select one)**
- [ ] Bug
- [x ] Feature Request 

**Please describe in detail the issue or the request:**
```
Make the bot a dalek. Cause. I'm sure Dan would approve.
```

**Comment by lolPants** [comment]
Please only use this for serious feature suggestions.

**Comment by RedMakuta** [comment]
Is it possible to delete this issue? I don't want my discord name floating around the internet anymore...
